# 추천 시스템

추천시스템은 사용자가 좋아할 가능성이 높은 아이템(영화, 제품, 음악 등)을 추천하는 시스템이다. 사용자와 아이템의 특성, 과거 상호작용, 유사성 등을 바탕으로 개인화된 추천을 제공한다.

추천 시스템의 주요 유형은 다음과 같다.

1. 콘텐츠 기반 필터링(Content-Based Filtering):
사용자가 과거에 선호한 아이템의 속성과 유사한 아이템을 추천하는 방식이다.
예를 들어 사용자가 액션 영화, SF 영화처럼 특정 장르를 자주 봤다면, 비슷한 장르나 속성을 가진 다른 영화를 추천할 수 있다.

2. 협업 필터링(Collaborative Filtering):
비슷한 사용자들의 행동 패턴이나, 함께 소비된 아이템의 관계를 바탕으로 추천하는 방식이다.
즉, 아이템 자체의 속성보다 사용자-아이템 상호작용 기록을 활용한다.

   2-1. 사용자 기반 협업 필터링:
   비슷한 구매나 평가 패턴을 가진 사용자들을 찾아 추천한다.
   예를 들어 홍길동이 라면, 만두, 김치를 구매했고 신사임당이 라면, 만두를 구매했다면, 두 사용자는 비슷한 소비 패턴을 보인다고 판단할 수 있다. 이 경우 신사임당에게 김치를 추천할 수 있다.

   2-2. 아이템 기반 협업 필터링:
   함께 구매되거나 함께 소비되는 경향이 높은 아이템을 추천한다.
   예를 들어 비빔면과 삼겹살을 같이 구매하는 경우가 많다면, 비빔면을 구매한 사용자에게 삼겹살을 추천할 수 있다.

3. 하이브리드 추천 시스템(Hybrid Recommendation Systems):
콘텐츠 기반 필터링과 협업 필터링을 결합한 방식이다.
협업 필터링은 신규 사용자나 신규 아이템에 대한 정보가 부족할 때 콜드 스타트 문제가 발생할 수 있다. 이를 보완하기 위해 하이브리드 방식은 초기에는 콘텐츠 정보도 활용하고, 이후 상호작용 데이터가 충분히 쌓이면 협업 신호를 함께 반영하여 추천 성능을 높인다.
넷플릭스와 같은 대규모 서비스는 이런 다양한 추천 신호를 복합적으로 활용하는 대표적인 사례로 볼 수 있다.

요즘 추천 시스템은 단순히 한 가지 알고리즘만 쓰기보다, 후보를 빠르게 찾는 단계와 그 후보를 정교하게 재정렬하는 단계를 나누어 여러 모델을 함께 사용하는 경우가 많다.

## 코사인 유사도 cosine similiarity

코사인 유사도(Cosine Similarity)는 두 벡터 간의 유사도를 측정하는 방법으로, 벡터의 방향을 비교하여 얼마나 유사한지를 계산하는 지표이다.

코사인 유사도의 값은 -1에서 1 사이에 있으며, 1에 가까울수록 두 벡터의 방향이 유사하다는 것을 의미한다. 주로 문서의 유사도를 계산하거나, 추천 시스템 등에서 사용된다.


**벡터란?**
벡터는 방향과 크기를 가진 데이터다.

집에서 학교까지 걸어간다고 할 때, 벡터로는 두 가지 정보를 나타낼 수 있다.
- 방향: 집에서 학교로 가는 길의 방향.
- 크기: 집에서 학교까지의 거리.

예를 들어, (1, 2)와 같은 2차원 좌표를 벡터라고 할 수 있다.

**Vector의 크기와 방향**

벡터의 방향과 크기를 따로 구할 수 있다.

1. **벡터의 크기 (Magnitude):** 벡터의 크기는 벡터의 각 성분을 제곱한 후 더한 값을 루트 씌운 것으로 구할 수 있다. 예를 들어, 2차원 벡터 $\vec{v} = (x, y)$의 크기는 다음과 같다.

   $
   \text{크기} = \sqrt{x^2 + y^2}
   $

   3차원 벡터의 경우, $\vec{v} = (x, y, z)$라면 크기는 다음과 같다.

   $
   \text{크기} = \sqrt{x^2 + y^2 + z^2}
   $

2. **벡터의 방향 (Direction):** 벡터의 방향은 벡터의 각 성분을 벡터의 크기로 나눈 정규화된 벡터로 구할 수 있다. 이를 단위 벡터라고도 한다. 벡터 $\vec{v} = (x, y)$의 경우 방향은 다음과 같이 구한다.

   $
   \text{단위 벡터} = \left(\frac{x}{\text{크기}}, \frac{y}{\text{크기}}\right)
   $

   3차원 벡터라면,

   $
   \text{단위 벡터} = \left(\frac{x}{\text{크기}}, \frac{y}{\text{크기}}, \frac{z}{\text{크기}}\right)
   $

In [84]:
import numpy as np

def vec_magnitude_direction(vec):
    # 크기 magnitude
    mag = np.sqrt(np.sum(vec ** 2))
    # 방향 (단위벡터)
    if mag != 0:
        dir = vec / mag
    else:
        dir = np.zeros_like(vec)
    return mag, dir

vec  = np.array([3, 4])
print(vec_magnitude_direction(vec))

vec  = np.array([3, 4, 5])
print(vec_magnitude_direction(vec))

(5.0, array([0.6, 0.8]))
(7.0710678118654755, array([0.42426407, 0.56568542, 0.70710678]))

### 두 벡터의 코사인 유사도

두 벡터가 얼마나 비슷한지 측정하는 방법이다. 코사인 유사도는 벡터의 방향을 기준으로 유사도를 측정한다.

**코사인 유사도의 수식**

코사인 유사도는 두 벡터 사이의 코사인을 계산한다. 벡터 $ A $와 $ B $가 주어지면, 코사인 유사도는 다음과 같이 계산된다:

$
Cosine Similarity = \frac{A \cdot B}{||A|| \times ||B||}
$

- $A \cdot B$는 두 벡터의 내적 (dot product)
- $||A||$와 $||B|| $는 각 벡터의 크기 (magnitude)

**코사인 유사도 계산 단계**

1. 벡터의 내적 계산

    두 벡터의 대응하는 원소들을 곱해서 모두 더한다.

    예: 벡터 $ A = (1, 2, 3) $와 $ B = (4, 5, 6) $일 때,

    $
    A \cdot B = (1 \times 4) + (2 \times 5) + (3 \times 6) = 4 + 10 + 18 = 32
    $

2. 벡터의 크기 계산

    각 벡터의 크기는 벡터 원소들의 제곱을 더한 후 제곱근을 취한다.

    예: 벡터 $ A $와 $ B $의 크기

    $||A|| = \sqrt{1^2 + 2^2 + 3^2} = \sqrt{1 + 4 + 9} = \sqrt{14}$
    <br>
    $||B|| = \sqrt{4^2 + 5^2 + 6^2} = \sqrt{16 + 25 + 36} = \sqrt{77}$

3. 코사인 유사도 계산

    내적을 벡터 크기의 곱으로 나눈다.

    $
    \text{Cosine Similarity} = \frac{32}{\sqrt{14} \times \sqrt{77}} = \frac{32}{\sqrt{1078}} = 0.9746318461970763
    $

4. 최종 값

    계산된 값을 통해 두 벡터의 유사도를 측정한다. 값이 1에 가까울수록 두 벡터는 더 유사하고, -1에 가까울수록 더 다르다.



코사인 유사도는 두 벡터가 얼마나 비슷한 방향을 가지고 있는지를 측정한다.

텍스트 분석 등에서 문서 간의 유사도를 계산하는 데 자주 사용된다. 계산 과정은 벡터의 내적과 크기를 구한 후 이를 이용해 최종적으로 유사도를 구하는 것이다.

텍스트 분석등에서는 count를 기반으로 하므로, 모든 vector가 0이상의 값이다. 즉 0~90° 사이의 값이고, 이에 따르는 코사인 유사도는 0 ~ 1 사이의 값이다.

In [85]:
vec_a = np.array([1, 2, 3])
# vec_a = np.array([-1, -2, -3])
vec_b = np.array([4, 5, 6])

def cos_similarity(A, B):
    # 두 벡터의 내적 / 두 벡터 크기 곱
    dot_product = A @ B
    norm_A = np.linalg.norm(A)
    norm_B = np.linalg.norm(B)
    return dot_product / (norm_A * norm_B)

cos_similarity(vec_a, vec_b)

0.9746318461970762

In [86]:
from sklearn.metrics.pairwise import cosine_similarity

vec_a = np.array([1, 2, 3]).reshape(1, -1)
vec_b = np.array([4, 5, 6]).reshape(1, -1)
print(vec_a, vec_b)

# batch차원으로 감싸진 vector를 전달해야 함
cosine_similarity(vec_a, vec_b)

[[1 2 3]] [[4 5 6]]

array([[0.97463185]])

## 컨텐츠 기반 필터링
순수하게 아이템기반으로 유사도를 따져서 추천

1. 컨텐츠의 여러 텍스트정보를 feature vector 변환
2. 코사인유사도 기반으로 컨테츠간 유사도 계산
3. 유사한 컨텐츠 중에서 평점이 좋은 순(가중평점)으로 추천

In [87]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## TMDB 5000 Movie Dataset 구조 이해

이 데이터는 영화 1편을 1행(row)으로 가지는 영화 메타데이터 중심 데이터셋이다.  
영화의 장르, 줄거리, 키워드, 평점, 투표 수, 인기도 같은 정보를 이용해 탐색적 분석이나 추천 시스템 실습을 하기에 적합하다.  
공식 Kaggle 설명에서도 plot, cast, crew, budget, revenue 등 수천 편 영화 정보를 다룰 수 있는 입문용 데이터로 소개된다.

보통 `tmdb_5000_movies.csv`와 `tmdb_5000_credits.csv` 두 파일로 구성된다.  
- movies 파일: 영화 자체의 메타데이터
- credits 파일: 출연진(cast), 제작진(crew) 정보

### 자주 보는 주요 컬럼

1. 영화 기본 식별 정보
- `id`: 영화 고유 ID
- `title`: 영화 제목
- `original_title`: 원제
- `original_language`: 원래 언어
- `release_date`: 개봉일
- `status`: 개봉 상태
- `homepage`: 공식 홈페이지

2. 내용(콘텐츠) 정보
- `genres`: 장르 목록
- `keywords`: 영화 핵심 키워드
- `overview`: 줄거리 요약
- `tagline`: 홍보 문구
- `spoken_languages`: 사용 언어

3. 제작 관련 정보
- `production_companies`: 제작사
- `production_countries`: 제작 국가
- `runtime`: 상영 시간
- `budget`: 제작비
- `revenue`: 흥행 수익

4. 평판/인기 정보
- `popularity`: 인기도 지표
- `vote_average`: 평균 평점
- `vote_count`: 평점 참여 수

5. 별도 credits 파일에서 자주 보는 컬럼
- `cast`: 배우 정보
- `crew`: 감독, 작가 등 제작진 정보 

### 이 데이터셋을 어떻게 바라보면 좋은가?

이 데이터는 크게 보면 다음 3덩어리로 나뉜다.

- 영화가 어떤 작품인가?  
  → `title`, `overview`, `genres`, `keywords`

- 영화가 얼마나 흥행/인기 있었는가?  
  → `popularity`, `vote_average`, `vote_count`, `revenue`

- 누가 만들고 출연했는가?  
  → `cast`, `crew`, `production_companies`

즉 추천 시스템 실습에서는 보통  
`genres`, `keywords`, `overview`, `cast`, `crew` 같은 콘텐츠 정보를 사용하고, 정렬이나 보정에는 `vote_average`, `vote_count`, `popularity`를 함께 활용한다.

In [88]:
movie_df = pd.read_csv('data/tmdb_5000_movies.csv')
columns = ['id', 'title', 'genres', 'vote_average', 'vote_count', 'popularity', 'keywords', 'overview']
movie_df = movie_df[columns]
movie_df.head()

,id,title,genres,vote_average,vote_count,popularity,keywords,overview
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",7.2,11800,150.437577,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",6.9,4500,139.082615,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",6.3,4466,107.376788,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",7.6,9106,112.312950,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",6.1,2124,43.926995,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca..."

In [89]:
movie_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            4803 non-null   int64
 1   title         4803 non-null   str
 2   genres        4803 non-null   str
 3   vote_average  4803 non-null   float64
 4   vote_count    4803 non-null   int64
 5   popularity    4803 non-null   float64
 6   keywords      4803 non-null   str
 7   overview      4800 non-null   str
dtypes: float64(2), int64(2), str(4)
memory usage: 300.3 KB

In [90]:
# ast.literaleval : 문자열로 저장된 파이썬 리터럴 표현을 실제 파이썬 객체로 안전하게 변환할 때 사용
#예 :  '[{'id':28,'name':'Action'}, ...]' -> [{'id':28,'name':'Action'},{'id':27'name':'Drama'}]
from ast import literal_eval

def parse_and_join_names(x):
    # 문자열이 실제 파이썬 객체(list)로 변환
    if isinstance(x,str):
        x=literal_eval(x)

    # 리스트가 아니면 빈 문자열 반환
    if not isinstance(x,list):
        return ''
    
    # 각 딕셔너리에서 name 값만 꺼내고 내부 공백은 제거한 뒤 하나의 문자열로 합침
    return ' '.join(
        item.get('name','').replace(' ','')
        for item in x
        if isinstance(item,dict)
    )

# genres, keywords 컬럼에 동일한 전처리 적용
for col in ['genres','keywords']:
    movie_df[col] = movie_df[col].apply(parse_and_join_names)

# 변환 결과 확인
movie_df

,id,title,genres,vote_average,vote_count,popularity,keywords,overview
0,19995,Avatar,Action Adventure Fantasy ScienceFiction,7.2,11800,150.437577,cultureclash future spacewar spacecolony socie...,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,Adventure Fantasy Action,6.9,4500,139.082615,ocean drugabuse exoticisland eastindiatradingc...,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,Action Adventure Crime,6.3,4466,107.376788,spy basedonnovel secretagent sequel mi6 britis...,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Action Crime Drama Thriller,7.6,9106,112.312950,dccomics crimefighter terrorist secretidentity...,Following the death of District Attorney Harve...
4,49529,John Carter,Action Adventure ScienceFiction,6.1,2124,43.926995,basedonnovel mars medallion spacetravel prince...,"John Carter is a war-weary, former military ca..."
...,...,...,...,...,...,...,...,...
4798,9367,El Mariachi,Action Crime Thriller,6.6,238,14.269792,unitedstates–mexicobarrier legs arms paperknif...,El Mariachi just wants to play his guitar and ...
4799,72766,Newlyweds,Comedy Romance,5.9,5,0.642552,,A newlywed couple's honeymoon is upended by th...
4800,231617,"Signed, Sealed, Delivered",Comedy Drama Romance TVMovie,7.0,6,1.444476,date loveatfirstsight narration investigation ...,"""Signed, Sealed, Delivered"" introduces a dedic..."
4801,126186,Shanghai Calling,,5.7,7,0.857008,,When ambitious New York attorney Sam is sent t...
4802,25975,My Date with Drew,Documentary,6.3,16,1.929883,obsession camcorder crush dreamgirl,Ever since the second grade when he first saw ...

## 장르 기반 코사인 유사도 계산

In [91]:
# 문자열을 숫자 벡터로 변환 (콘텐츠 기반 추천에서는 영화 간 유사도 계산이 필요하므로 문자열 -> 숫자 변환 필요)
# CountVectorizer: 각 토큰이 문서에 몇 번 등장했는지를 기반으로 벡터화
from sklearn.feature_extraction.text import CountVectorizer

# ngram_range
# : 1개 단어 토큰(unigram)과 2개 단어 토큰(bigram) 등을 고려할 수 있다
cnt_vectorizer = CountVectorizer(ngram_range=(1, 1))

# 1) 전체 영화의 genres 컬럼을 보고 장르 토큰 사전을 만든다
# 2) 각 영화마다 어떤 토큰이 등장했는지 횟수를 센다
# 3) 각 영화를 숫자 벡터로 변환한다
movie_genre_mat = cnt_vectorizer.fit_transform(movie_df['genres'])

# CountVectorizer가 생성한 단어 사전
print(cnt_vectorizer.vocabulary_)

# 행: 영화 개수, 열: 전체 장르 토큰 개수
print(movie_genre_mat.shape)

# 앞 부분 일부만 배열 형태로 확인
movie_genre_mat[:20, :20].toarray()

{'action': 0, 'adventure': 1, 'fantasy': 8, 'sciencefiction': 15, 'crime': 4, 'drama': 6, 'thriller': 16, 'animation': 2, 'family': 7, 'western': 19, 'comedy': 3, 'romance': 14, 'horror': 11, 'mystery': 13, 'history': 10, 'war': 18, 'music': 12, 'documentary': 5, 'foreign': 9, 'tvmovie': 17}
(4803, 20)

array([[1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int64)

In [92]:
# 영화간 장르 유사도 비교
genre_sim = cosine_similarity(movie_genre_mat, movie_genre_mat)
print(genre_sim.shape)
genre_sim[:10, :10]

(4803, 4803)

array([[1.        , 0.8660254 , 0.57735027, 0.25      , 0.8660254 ,
        0.8660254 , 0.        , 0.8660254 , 0.57735027, 0.8660254 ],
       [0.8660254 , 1.        , 0.66666667, 0.28867513, 0.66666667,
        1.        , 0.        , 0.66666667, 0.66666667, 1.        ],
       [0.57735027, 0.66666667, 1.        , 0.57735027, 0.66666667,
        0.66666667, 0.        , 0.66666667, 0.33333333, 0.66666667],
       [0.25      , 0.28867513, 0.57735027, 1.        , 0.28867513,
        0.28867513, 0.        , 0.28867513, 0.        , 0.28867513],
       [0.8660254 , 0.66666667, 0.66666667, 0.28867513, 1.        ,
        0.66666667, 0.        , 1.        , 0.33333333, 0.66666667],
       [0.8660254 , 1.        , 0.66666667, 0.28867513, 0.66666667,
        1.        , 0.        , 0.66666667, 0.66666667, 1.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        , 0.40824829, 0.        ],
       [0.8660254 , 0.66666667, 0.66666667, 0.28867513, 1.        ,
        0.66666667, 0.        , 1.        , 0.33333333, 0.66666667],
       [0.57735027, 0.66666667, 0.33333333, 0.        , 0.33333333,
        0.66666667, 0.40824829, 0.33333333, 1.        , 0.66666667],
       [0.8660254 , 1.        , 0.66666667, 0.28867513, 0.66666667,
        1.        , 0.        , 0.66666667, 0.66666667, 1.        ]])

In [93]:
# 각 영화별 다른 영화들과의 유사도를 오름차순으로 정렬한 뒤, 열 순서를 뒤집어 내림차순(유사도 높은 순) 인덱스를 만든다.
movie_idx_by_genre_sim_desc = genre_sim.argsort(axis=-1)[:, ::-1]
print(movie_idx_by_genre_sim_desc.shape)

# 0번 영화와 유사도가 가장 높은 10개 영화의 인덱스
print(movie_idx_by_genre_sim_desc[0, :10])

(4803, 4803)
[   0  870   46   10  232  813 3494   61   14 1652]

In [94]:
# 0번 영화와 유사도가 가장 높은 10개의 영화
movie_df.iloc[movie_idx_by_genre_sim_desc[0, :10]]

,id,title,genres,vote_average,vote_count,popularity,keywords,overview
0,19995,Avatar,Action Adventure Fantasy ScienceFiction,7.2,11800,150.437577,cultureclash future spacewar spacecolony socie...,"In the 22nd century, a paraplegic Marine is di..."
870,8536,Superman II,Action Adventure Fantasy ScienceFiction,6.5,629,30.515175,savingtheworld dccomics sequel superhero based...,Three escaped criminals from the planet Krypto...
46,127585,X-Men: Days of Future Past,Action Adventure Fantasy ScienceFiction,7.5,6032,118.078691,1970s mutant timetravel marvelcomic basedoncom...,The ultimate X-Men ensemble fights a war for t...
10,1452,Superman Returns,Adventure Fantasy Action ScienceFiction,5.4,1400,57.925623,savingtheworld dccomics invulnerability sequel...,Superman returns to discover his 5-year absenc...
232,76170,The Wolverine,Action ScienceFiction Adventure Fantasy,6.3,4053,15.953444,japan samurai mutant worldwari marvelcomic sup...,Wolverine faces his ultimate nemesis - and tes...
813,1924,Superman,Action Adventure Fantasy ScienceFiction,6.9,1022,48.507081,savingtheworld journalist dccomics crimefighte...,Mild-mannered Clark Kent works as a reporter a...
3494,27549,Beastmaster 2: Through the Portal of Time,Action Adventure Fantasy ScienceFiction,4.6,17,1.478505,basedonnovel timetravel sequel psychotronic sw...,"Mark Singer returns as Dar, the warrior who ca..."
61,76757,Jupiter Ascending,ScienceFiction Fantasy Action Adventure,5.2,2768,85.369080,jupiter space womandirector 3d interspeciesrom...,In a universe where human genetic material is ...
14,49521,Man of Steel,Action Adventure Fantasy ScienceFiction,6.5,6359,99.398009,savingtheworld dccomics superhero basedoncomic...,A young boy learns that he has extraordinary p...
1652,14164,Dragonball Evolution,Action Adventure Fantasy ScienceFiction Thriller,2.9,462,21.677732,karate superhero revenge dragon duringcreditss...,The young warrior Son Goku sets out on a quest...

In [95]:
# 영화 대부와 높은 장르 유사도를 가진 영화 조회
title = 'The Godfather'
index = movie_df[movie_df['title'] == title].index.values[0]
rcmd_movie_df = movie_df.iloc[movie_idx_by_genre_sim_desc[index, :20]]
rcmd_movie_df.sort_values('vote_average', ascending=False)[:10]

,id,title,genres,vote_average,vote_count,popularity,keywords,overview
3337,238,The Godfather,Drama Crime,8.4,5893,143.659698,italy loveatfirstsight lossoffather patriarch ...,"Spanning the years 1945 to 1955, a chronicle o..."
1663,311,Once Upon a Time in America,Drama Crime,8.2,1069,49.336397,lifeanddeath corruption streetgang rape sadist...,A former Prohibition-era Jewish gangster retur...
3866,598,City of God,Drama Crime,8.1,1814,44.356711,malenudity streetgang brazilian photographer 1...,Cidade de Deus is a shantytown that started du...
3701,641,Requiem for a Dream,Crime Drama,7.9,2443,11.573034,drugaddiction junkie heroin speed diet unsocia...,The hopes and dreams of four ambitious people ...
3887,627,Trainspotting,Drama Crime,7.8,2655,63.513324,londonengland alcohol sex basedonnovel drugadd...,"Renton, deeply immersed in the Edinburgh drug ..."
883,640,Catch Me If You Can,Drama Crime,7.7,3795,73.944049,conman biography fbiagent overheadcamerashot a...,"A true story about Frank Abagnale Jr. who, bef..."
3699,1429,25th Hour,Crime Drama,7.2,629,30.196039,prison prisoner dream drugdealer nightclub ame...,The filmed adaptation from David Benioff's nov...
2448,10673,Wall Street,Crime Drama,7.0,546,24.898687,power fraud broker wallstreet finances lawyer ...,A young and impatient stockbroker is willing t...
2839,10220,Rounders,Drama Crime,6.9,439,18.422008,gambling law compulsivegambling roulette gain,A young man is a reformed gambler who must ret...
3348,398,Capote,Crime Drama,6.8,384,17.434862,gay self-fulfillingprophecy basedonnovel journ...,"A biopic of the writer, Truman Capote and his ..."

In [96]:
# 영화명을 전달하면 장르 유사도가 높은 영화 중 평점이 상위인 영화 10건을 추천하는 함수
def recommand_genre_similar_movies(title, top_n=10):
    # 제목으로 영화 인덱스 조회
    index = movie_df[movie_df['title'] == title].index.values[0]
    # 장르 유사도 상위 top_n * 2 조회
    rcmd_movie_df = movie_df.iloc[movie_idx_by_genre_sim_desc[index, :top_n * 2]]
    # 조회한 영화는 제외
    rcmd_movie_df = rcmd_movie_df[rcmd_movie_df.index != index]
    # 평점 상위 top_n 건 추천
    return rcmd_movie_df.sort_values('vote_average', ascending=False)[:top_n]

recommand_genre_similar_movies('Signed, Sealed, Delivered', 15)

,id,title,genres,vote_average,vote_count,popularity,keywords,overview
3906,284,The Apartment,Comedy Drama Romance,8.1,483,22.889294,newyork newyear'seve lovesickness agedifferenc...,Bud Baxter is a minor clerk in a huge New York...
3440,338,"Good bye, Lenin!",Comedy Drama Romance,7.4,586,11.086001,bureaucracy berlinwall policestate coma lossof...,An affectionate and refreshing East/West-Germa...
3339,19913,(500) Days of Summer,Comedy Drama Romance,7.2,2904,45.610993,date sex jealousy fight architect gallery inte...,"Tom (Joseph Gordon-Levitt), greeting-card writ..."
3334,7326,Juno,Comedy Drama Romance,7.0,2244,19.782725,sexuality becominganadult puberty firsttime os...,A young girl named Juno gets herself pregnant ...
4331,26815,Rocket Singh: Salesman of the Year,Drama Comedy Romance,7.0,27,3.000435,ambition bollywood business india strugglingca...,Rocket Singh - Salesman of the Year is the som...
2549,10564,Where the Heart Is,Comedy Drama Romance,6.9,155,6.857923,california baby supermarket oklahoma pregnancy...,Novalee Nation is a 17-year-old Tennessee tran...
2059,21494,Moliere,Romance Drama Comedy,6.7,45,4.613350,playwright,"Molière, a down-and-out actor-cum-playwright u..."
4355,113947,The Sessions,Drama Romance Comedy,6.6,179,9.115486,cat virgin narration wheelchair graduation sex...,Though a childhood bout with polio left him de...
4588,11240,My Beautiful Laundrette,Romance Drama Comedy,6.6,51,3.703005,londonengland gay immigration society british ...,"Omar, a homosexual Pakistani boy living in Lon..."
3422,25113,The Four Seasons,Comedy Drama Romance,6.3,16,8.067702,,Three middle-aged wealthy couples take vacatio...
3973,44594,Barry Munday,Comedy Drama Romance,6.3,22,1.975941,basedonnovel letter paternity castration docto...,"Barry Munday, a libido-driven wage slave who s..."
2677,62008,Good Deeds,Comedy Drama Romance,6.2,45,4.448494,africanamerican singlemother fiancéfiancéerela...,Businessman Wesley Deeds is jolted out of his ...
2600,9686,New York Stories,Comedy Drama Romance,6.2,64,6.684096,newyork mother hotel robbery jealousy obsessio...,Three stories happening in New York. The first...
3376,39053,Cyrus,Comedy Drama Romance,6.1,133,15.212569,mumblecore,With John's social life at a standstill and hi...
1232,38357,Morning Glory,Comedy Drama Romance,6.1,412,22.491388,workethic tvmorningshow tvreporter,A young and devoted morning television produce...

### 평가 횟수에 대한 가중치가 부여된 평점(Weighted Rating) 적용


$$
가중 평점(Weighted Rating) = (v/(v+m)) * R + (m/(v+m)) * C
$$


| 기호 | 의미                        | 예시      |
| -- | ------------------------- | ------- |
| v  | 이 영화에 평점을 준 사람 수 vote_count         | 예: 30명  |
| R  | 이 영화의 평균 평점 vote_average               | 예: 9.0점 |
| m  | 믿을 만한 평가가 되려면 필요한 최소 평가 수. 임계치 설정 | 예: 100명 |
| C  | 전체 영화의 평균 평점. 전체적으로 평점이 후한 편인지, 박한 편인지 반영. vote_average               | 예: 7.0점 |

In [97]:
# vote_count 분포
movie_df['vote_count'].describe()

count     4803.000000
mean       690.217989
std       1234.585891
min          0.000000
25%         54.000000
50%        235.000000
75%        737.000000
max      13752.000000
Name: vote_count, dtype: float64

In [98]:
# 최소 투표수 임계치 설정
m = movie_df['vote_count'].quantile(0.6)        # 상위 40% 수치
print(m)

# 전체 영화 평점
C = movie_df['vote_average'].mean()
print(C)

370.1999999999998
6.092171559442016

In [99]:
# 가중 평점 연산 함수
def weighted_vote_average(movie):
    v = movie['vote_count']
    R = movie['vote_average']
    return (v/(v+m))*R + (m/(v+m))*C

movie_df['weighted_vote_average'] = movie_df.apply(weighted_vote_average,axis=1)
movie_df

,id,title,genres,vote_average,vote_count,popularity,keywords,overview,weighted_vote_average
0,19995,Avatar,Action Adventure Fantasy ScienceFiction,7.2,11800,150.437577,cultureclash future spacewar spacecolony socie...,"In the 22nd century, a paraplegic Marine is di...",7.166301
1,285,Pirates of the Caribbean: At World's End,Adventure Fantasy Action,6.9,4500,139.082615,ocean drugabuse exoticisland eastindiatradingc...,"Captain Barbossa, long believed to be dead, ha...",6.838594
2,206647,Spectre,Action Adventure Crime,6.3,4466,107.376788,spy basedonnovel secretagent sequel mi6 britis...,A cryptic message from Bond’s past sends him o...,6.284091
3,49026,The Dark Knight Rises,Action Crime Drama Thriller,7.6,9106,112.312950,dccomics crimefighter terrorist secretidentity...,Following the death of District Attorney Harve...,7.541095
4,49529,John Carter,Action Adventure ScienceFiction,6.1,2124,43.926995,basedonnovel mars medallion spacetravel prince...,"John Carter is a war-weary, former military ca...",6.098838
...,...,...,...,...,...,...,...,...,...
4798,9367,El Mariachi,Action Crime Thriller,6.6,238,14.269792,unitedstates–mexicobarrier legs arms paperknif...,El Mariachi just wants to play his guitar and ...,6.290894
4799,72766,Newlyweds,Comedy Romance,5.9,5,0.642552,,A newlywed couple's honeymoon is upended by th...,6.089611
4800,231617,"Signed, Sealed, Delivered",Comedy Drama Romance TVMovie,7.0,6,1.444476,date loveatfirstsight narration investigation ...,"""Signed, Sealed, Delivered"" introduces a dedic...",6.106650
4801,126186,Shanghai Calling,,5.7,7,0.857008,,When ambitious New York attorney Sam is sent t...,6.084894
4802,25975,My Date with Drew,Documentary,6.3,16,1.929883,obsession camcorder crush dreamgirl,Ever since the second grade when he first saw ...,6.100782

In [100]:
# 영화명을 전달하면 장르 유사도가 높은 영화 중 '가중평점'이 상위인 영화 10건을 추천하는 함수
def recommand_genre_similar_movies(title, top_n=10):
    # 제목으로 영화 인덱스 조회
    try:
        index = movie_df[movie_df['title'] == title].index.values[0]
    except:
        raise ValueError(f'해당 영화는 존재하지 않습니다. : {title}')
    # 장르 유사도 상위 top_n * 2 조회
    rcmd_movie_df = movie_df.iloc[movie_idx_by_genre_sim_desc[index, :top_n * 2]]
    # 조회한 영화는 제외
    rcmd_movie_df = rcmd_movie_df[rcmd_movie_df.index != index]
    # 평점 상위 top_n 건 추천
    return rcmd_movie_df.sort_values('weighted_vote_average', ascending=False)[:top_n]

recommand_genre_similar_movies('Avatar', 10)

,id,title,genres,vote_average,vote_count,popularity,keywords,overview,weighted_vote_average
46,127585,X-Men: Days of Future Past,Action Adventure Fantasy ScienceFiction,7.5,6032,118.078691,1970s mutant timetravel marvelcomic basedoncom...,The ultimate X-Men ensemble fights a war for t...,7.418594
322,18,The Fifth Element,Adventure Fantasy Action Thriller ScienceFiction,7.3,3885,109.528572,clone taxi cyborg egypt future stowaway spacet...,"In 2257, a taxi driver is unintentionally give...",7.194920
813,1924,Superman,Action Adventure Fantasy ScienceFiction,6.9,1022,48.507081,savingtheworld journalist dccomics crimefighte...,Mild-mannered Clark Kent works as a reporter a...,6.685190
14,49521,Man of Steel,Action Adventure Fantasy ScienceFiction,6.5,6359,99.398009,savingtheworld dccomics superhero basedoncomic...,A young boy learns that he has extraordinary p...,6.477564
870,8536,Superman II,Action Adventure Fantasy ScienceFiction,6.5,629,30.515175,savingtheworld dccomics sequel superhero based...,Three escaped criminals from the planet Krypto...,6.348901
232,76170,The Wolverine,Action ScienceFiction Adventure Fantasy,6.3,4053,15.953444,japan samurai mutant worldwari marvelcomic sup...,Wolverine faces his ultimate nemesis - and tes...,6.282606
3208,333355,Star Wars: Clone Wars: Volume 1,Action Adventure Animation Fantasy ScienceFiction,8.0,27,1.881466,war spaceopera clonetroopers,"The Saga continues with the Emmy-winning ""Star...",6.221858
1390,12437,Underworld: Rise of the Lycans,Fantasy Action Adventure ScienceFiction Thriller,6.2,1428,51.927471,prison underworld slavery castle vampire war w...,"A prequel to the first two Underworld films, t...",6.177801
1191,11551,Small Soldiers,Comedy Adventure Fantasy ScienceFiction Action,6.2,511,23.088571,defenseindustry toyshop technicaltoy soldier p...,When missile technology is used to enhance toy...,6.154700
1932,24264,Sheena,Action Adventure Comedy Fantasy ScienceFiction,5.0,22,4.020194,africa mercenary adventure femalehero junglegirl,Sheena's white parents are killed while on Saf...,6.030907

## genres + keywords 를 함께 사용한 콘텐츠 기반 필터링
genres와 keywords를 하나의 텍스트로 합친 뒤 다시 벡터화 하여, 장르만 사용했을 때와 추천 결과가 어떻게 달라지는지 비교해본다.

In [101]:
movie_df['genres + keywords'] = movie_df['genres'] + movie_df['keywords']
movie_df['genres + keywords'][0]

'Action Adventure Fantasy ScienceFictioncultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d'

In [102]:
from sklearn.feature_extraction.text import CountVectorizer

cnt_vectorizer = CountVectorizer(ngram_range=(1, 1))

movie_genkey_mat = cnt_vectorizer.fit_transform(movie_df['genres + keywords'])

print(cnt_vectorizer.vocabulary_)

print(movie_genkey_mat.shape)

movie_genkey_mat[:20, :20].toarray()

{'action': 44, 'adventure': 156, 'fantasy': 4279, 'sciencefictioncultureclash': 9601, 'future': 4765, 'spacewar': 10295, 'spacecolony': 10279, 'society': 10212, 'spacetravel': 10294, 'futuristic': 4769, 'romance': 9006, 'space': 10274, 'alien': 325, 'tribe': 11566, 'alienplanet': 338, 'cgi': 1651, 'marine': 6729, 'soldier': 10227, 'battle': 899, 'loveaffair': 6565, 'antiwar': 510, 'powerrelations': 8386, 'mindandsoul': 6975, '3d': 21, 'actionocean': 96, 'drugabuse': 3634, 'exoticisland': 3961, 'eastindiatradingcompany': 3714, 'loveofone': 6574, 'slife': 10129, 'traitor': 11509, 'shipwreck': 9970, 'strongwoman': 10549, 'ship': 9967, 'alliance': 353, 'calypso': 1452, 'afterlife': 268, 'fighter': 4500, 'pirate': 8178, 'swashbuckler': 10695, 'aftercreditsstinger': 267, 'crimespy': 2668, 'basedonnovel': 863, 'secretagent': 9790, 'sequel': 9859, 'mi6': 6919, 'britishsecretservice': 1297, 'unitedkingdom': 11720, 'crime': 2526, 'drama': 3233, 'thrillerdccomics': 11077, 'crimefighter': 2587, 'terrorist': 10895, 'secretidentity': 9799, 'burglar': 1380, 'hostagedrama': 5633, 'timebomb': 11388, 'gothamcity': 5004, 'vigilante': 11847, 'cover': 2489, 'up': 11742, 'superhero': 10628, 'villainess': 11856, 'tragichero': 11491, 'terrorism': 10894, 'destruction': 2996, 'catwoman': 1613, 'catburglar': 1591, 'imax': 5762, 'flood': 4606, 'criminalunderworld': 2705, 'batman': 895, 'sciencefictionbasedonnovel': 9581, 'mars': 6749, 'medallion': 6821, 'princess': 8454, 'steampunk': 10445, 'martian': 6758, 'escape': 3872, 'edgarriceburroughs': 3736, 'alienrace': 341, 'superhumanstrength': 10634, 'marscivilization': 6750, 'swordandplanet': 10725, '19thcentury': 15, 'adventuredualidentity': 183, 'amnesia': 406, 'sandstorm': 9468, 'forgiveness': 4669, 'spider': 10331, 'wretch': 12295, 'deathofafriend': 2890, 'egomania': 3745, 'sand': 9464, 'narcism': 7491, 'hostility': 5640, 'marvelcomic': 6762, 'revenge': 8904, 'animation': 461, 'familyhostage': 4171, 'magic': 6634, 'horse': 5620, 'fairytale': 4045, 'musical': 7245, 'tower': 11462, 'blondewoman': 1115, 'selfishness': 9833, 'healingpower': 5226, 'basedonfairytale': 857, 'duringcreditsstinger': 3686, 'healinggift': 5225, 'animalsidekick': 453, 'sciencefictionmarvelcomic': 9658, 'basedoncomicbook': 855, 'vision': 11878, 'superheroteam': 10632, 'marvelcinematicuniverse': 6761, 'familywitch': 4264, 'broom': 1326, 'schoolofwitchcraft': 9549, 'wizardry': 12229, 'apparition': 527, 'teenagecrush': 10828, 'werewolf': 12094, 'fantasydccomics': 4298, 'superpowers': 10645, 'clarkkent': 1854, 'brucewayne': 1337, 'dcextendeduniverse': 2860, 'sciencefictionsavingtheworld': 9688, 'dccomics': 2859, 'invulnerability': 5941, 'kryptonite': 6237, 'lexluthor': 6378, 'thriller': 10975, 'crimekilling': 2617, 'undercover': 11688, 'actionwitch': 126, 'fortuneteller': 4681, 'bondage': 1183, 'monster': 7099, 'captain': 1504, 'cardgame': 1520, 'compass': 2312, 'daughter': 2850, 'westerntexas': 12134, 'survivor': 10677, 'texasranger': 10910, 'partner': 7988, 'outlaw': 7872, 'lawyer': 6328, 'train': 11497, 'loneranger': 6494, 'comanche': 1961, 'theloneranger': 10939, 'tonto': 11423, 'superhuman': 10633, 'alieninvasion': 334, 'reboot': 8724, 'family': 4077, 'fantasybasedonnovel': 4285, 'fictionalplace': 4492, 'brothersisterrelationship': 1333, 'lion': 6434, 'humanbeing': 5669, 'leapintime': 6333, 'matteroflifeanddeath': 6801, 'faith': 4046, 'uncle': 11681, 'narnia': 7499, 'fantasyworld': 4380, 'sciencefiction': 9561, 'adventurenewyork': 218, 'shield': 9963, 'fantasysea': 4358, 'mutiny': 7351, 'sword': 10724, 'primeminister': 8448, 'sailing': 9437, 'silver': 10053, 'duke': 3679, 'mermaid': 6887, 'comedy': 1969, 'sciencefictiontimetravel': 9717, 'timemachine': 11392, 'fictionalgovernmentagency': 4488, 'seeingthefuture': 9821, 'changinghistory': 1671, 'fantasycorruption': 4296, 'elves': 3784, 'dwarves': 3691, 'orcs': 7839, 'middle': 6927, 'earth': 3704, 'tolkien': 11416, 'hobbit': 5431, 'dragon': 3227, 'unlikelyfriendship': 11726, 'epicbattle': 3854, 'swordandsorcery': 10727, 'fantasylossoffather': 4332, 'serum': 9869, 'scientificexperiment': 9735, 'spiderbite': 10332, 'maskedvigilante': 6774, 'geneticengineering': 4856, 'socialoutcast': 10206, 'adventurerobinhood': 226, 'archer': 555, 'knight': 6221, 'sherwoodforest': 9962, 'bowandarrow': 1221, 'middleages': 6931, 'medieval': 6837, 'kingofengland': 6204, 'fantasyelves': 4307, 'wizard': 12228, 'fantasyengland': 4308, 'experiment': 3970, 'lordship': 6510, 'polarbear': 8255, 'orphan': 7857, 'animal': 440, 'basedonyoungadultnovel': 876, 'actionfilmbusiness': 72, 'screenplay': 9751, 'showbusiness': 10015, 'filmmaking': 4525, 'filmproducer': 4527, 'indigenous': 5815, 'dinosaur': 3037, 'thrillershipwreck': 11300, 'iceberg': 5719, 'panic': 7928, 'titanic': 11402, 'oceanliner': 7751, 'epic': 3853, 'richwoman': 8931, 'poorman': 8329, 'love': 6564, 'disaster': 3053, 'tragiclove': 11492, 'classdifferences': 1857, 'starcrossedlovers': 10422, 'steerage': 10449, 'salvage': 9455, 'richsnob': 8929, '1910s': 5, 'sciencefictioncivilwar': 9594, 'war': 11936, 'sciencefictionfight': 9626, 'navy': 7529, 'mindreading': 6979, 'hongkong': 5479, 'soccer': 10190, 'scientist': 9737, 'fictionalwar': 4494, 'naval': 7524, 'armada': 574, 'battleship': 908, 'navalcombat': 7526, 'jdsmyoko': 6033, 'lostcommunication': 6550, 'taser': 10793, 'buoy': 1378, 'communicationsexpert': 2305, 'jointchiefsofstaff': 6088, 'crashlanding': 2507, 'jetfighterpilot': 6053, 'navylieutenant': 7530, 'permissiontomarry': 8064, 'ussjohnpauljones': 11763, 'basedonboardgame': 852, 'mightymo': 6942, 'ussmissouri': 11764, 'thrillermonster': 11211, 'dna': 3103, 'tyrannosaurusrex': 11666, 'velociraptor': 11800, 'island': 5974, 'suspense': 10681, 'amusementpark': 411, 'animalattack': 442, 'themepark': 10940, 'jurassicpark': 6126, 'animalhorror': 445, 'thrillerspy': 11316, 'sociopath': 10215, 'killer': 6184, 'artgallery': 603, 'istanbulturkey': 5983, 'uzi': 11768, 'boobytrap': 1188, 'impersonatingapoliceofficer': 5776, 'macao': 6609, 'fantasydualidentity': 4305, 'pizzaboy': 8194, 'doctor': 3107, 'tentacle': 10884, 'death': 2884, 'supervillain': 10650, 'sciencefictionterrorist': 9716, 'waronterror': 11995, 'tennessee': 10877, 'malibu': 6672, 'tonystark': 11425, 'ironman': 5968, 'mandarin': 6688, 'warmachine': 11985, 'ironpatriot': 5969, 'extremis': 4015, 'adventurebasedonnovel': 167, 'queen': 8613, 'aliceinwonderland': 324, 'thrillermutant': 11216, 'beast': 924, 'cyclops': 2796, 'familymonster': 4192, 'dormitory': 3206, 'games': 4793, 'bestfriend': 985, 'university': 11725, 'scary': 9527, 'adventureegypt': 186, 'sun': 10617, 'chaos': 1675, 'symbol': 10734, 'artifact': 607, 'transformers': 11516, 'tank': 10780, 'robot': 8971, 'adventuresequel': 232, 'giantrobot': 4909, 'transformingrobot': 11517, 'familycircus': 4114, 'witch': 12217, 'hope': 5487, 'illusion': 5752, 'lost': 6544, 'magictrick': 6641, 'fantasyobsession': 4346, 'electrocution': 3764, 'medicalexperiment': 6829, 'electricity': 3762, 'sciencefictionartificialintelligence': 9576, 'computerprogram': 2325, 'dystopia': 3701, 'computer': 2319, 'deception': 2918, 'duel': 3676, 'motorcycle': 7156, 'neonlight': 7563, 'autocracy': 712, 'comedycarrace': 2018, 'anthropomorphism': 496, 'sciencefictiondccomics': 9604, 'transformation': 11515, 'alieninfection': 333, 'magicalobject': 6636, 'protector': 8520, 'origin': 7852, 'comedyhostage': 2102, 'college': 1939, 'toy': 11471, 'barbie': 825, 'daycare': 2852, 'teddybear': 10826, 'toycomestolife': 11472, 'personification': 8073, 'inanimateobjectscomingtolife': 5791, 'toystory': 11477, 'thrillersavingtheworld': 11280, 'artificialintelligence': 610, 'prophecy': 8508, 'sanfrancisco': 9471, 'cyborg': 2794, 'killerrobot': 6189, 'gasstation': 4829, 'post': 8359, 'apocalyptic': 520, 'army': 585, 'firearm': 4541, 'wartime': 12022, 'losangeles': 6513, 'actioncarrace': 56, 'speed': 10316, 'car': 1511, 'race': 8624, 'musclecar': 7235, 'horror': 5493, 'thrillerdystopia': 11093, 'apocalypse': 519, 'zombie': 12359, 'nuclearweapons': 7710, 'multipleperspectives': 7212, 'zombieapocalypse': 12360, 'sciencefiction1970s': 9562, 'mutant': 7346, 'timetravel': 11397, 'storm': 10496, 'changingthepastorfuture': 1672, 'sciencefictionspacecraft': 9706, 'friendship': 4737, 'spaceopera': 10287, 'terroristbombing': 10897, 'fantasybasedonfairytale': 4284, 'giant': 4902, 'romancebasedonnovel': 9036, 'infidelity': 5832, 'obsession': 7741, 'romancepersia': 9229, 'brotheragainstbrother': 1329, 'armageddon': 576, 'regent': 8801, 'basedonvideogame': 875, 'adventuredystopia': 185, 'giantmonster': 4907, 'adventuremoon': 215, 'spacecraft': 10280, 'bodyguard': 1161, 'basedoncartoon': 853, 'sabotage': 9415, 'worddomination': 12260, 'commando': 2294, 'actionsavingtheworld': 106, 'riddle': 8932, 'whip': 12152, 'treasure': 11552, 'mexicocity': 6917, 'leatherjacket': 6339, 'machinegun': 6614, 'alienphenomenons': 337, 'mayacivilization': 6806, 'peru': 8078, 'treasurehunt': 11553, 'nuclearexplosion': 7702, 'refrigerator': 8795, 'archaeologist': 549, 'indianajones': 5804, 'archeology': 554, 'familytyrannosaurusrex': 4252, 'friends': 4736, 'alternatehistory': 368, 'fear': 4419, 'nature': 7521, 'human': 5667, 'journey': 6094, 'fantasyscotland': 4357, 'rebel': 8719, 'bravery': 1258, 'kingdom': 6203, 'wish': 12214, 'bear': 919, 'scot': 9744, 'rebelliousdaughter': 8721, 'turnsintoanimal': 11628, 'archery': 556, 'ruins': 9385, 'peaceoffering': 8020, 'womandirector': 12240, 'courage': 2478, 'sciencefictionsequel': 9694, 'stranded': 10509, 'hatred': 5198, 'familyromanticcomedy': 4223, 'thrillerambassador': 10986, 'sciencefictioncivilization': 9593, 'naturaldisaster': 7518, 'endoftheworld': 3812, 'volcaniceruption': 11889, 'mayan': 6807, 'ark': 571, 'solar': 10223, 'destructionofmankind': 2999, 'dramaholiday': 3397, 'victorianengland': 11824, 'money': 7080, 'christmaseve': 1808, 'scrooge': 9756, 'christmascarol': 1807, 'ghost': 4891, 'lesson': 6367, 'charlesdickens': 1688, 'christmas': 1806, 'adventurejupiter': 203, 'interspeciesromance': 5912, 'adventureafrica': 159, 'feralchild': 4469, 'tarzan': 10792, 'jungle': 6116, 'fantasysavingtheworld': 4356, 'selfsacrifice': 9836, 'winter': 12206, 'cupboard': 2769, 'beaver': 939, 'fairy': 4043, 'talefigure': 10754, 'sciencefictionmutant': 9663, 'supernaturalpowers': 10642, 'worlddomination': 12276, '1980s': 12, 'scarecrow': 9525, 'sadism': 9418, 'joker': 6089, 'organizedcrime': 7847, 'criminalmastermind': 2702, 'districtattorney': 3085, 'adventureagedifference': 160, 'centralandsouthamerica': 1644, 'balloon': 788, 'floatingintheair': 4602, 'exploring': 3993, 'sciencefictionalien': 9566, 'adventuremiddleeast': 212, 'armsdealer': 583, 'counterterrorism': 2463, 'agentcoulson': 271, 'familylibrary': 4182, 'clock': 1889, 'filmdirector': 4515, 'key': 6170, 'boy': 1234, 'automaton': 714, 'hiding': 5297, 'legbrace': 6350, 'doberman': 3104, 'westernsteampunk': 12133, 'basedontvseries': 874, 'steamlocomotive': 10444, 'drag': 3225, 'shareduniverse': 9947, 'antihero': 502, 'secretmission': 9805, 'villain': 11855, 'familyfathersonrelationship': 4145, 'dailylife': 2803, 'marriedcouple': 6747, 'support': 10652, 'father': 4404, 'marriage': 6740, 'baustelle': 909, 'rescue': 8861, 'noah': 7658, 'sark': 9484, 'sciencefictiondejavu': 9605, 'timewarp': 11399, 'restart': 8880, 'militaryofficer': 6956, 'exoskeleton': 3959, 'tattoo': 10796, 'water': 12042, 'doomsday': 3197, 'secret': 9789, 'hostage': 5632, 'technology': 10825, 'warhead': 11966, 'government': 5011, 'president': 8427, 'murder': 7224, 'attack': 669, 'explosion': 3994, 'lasers': 6291, 'evil': 3910, 'cobra': 1916, 'familydream': 4136, 'cartoon': 1557, 'imaginaryfriend': 5758, 'moving': 7197, 'kids': 6181, 'unicorn': 11716, 'emotions': 3799, 'snake': 10163, 'wolf': 12231, 'elephant': 3770, 'tiger': 11384, 'panther': 7929, 'remake': 8833, 'talkinganimal': 10762, 'talkingtoanimals': 10767, 'sciencefictionmalibu': 9654, 'dramaqueen': 3514, 'immortality': 5769, 'forest': 4667, 'woman': 12237, 'eternalyouth': 3895, 'snowwhite': 10186, 'evilqueen': 3926, 'evilstepmother': 3928, 'imprisoned': 5786, 'sorceress': 10246, 'romancefairytale': 9118, 'sleepingbeauty': 10123, 'darkfantasy': 2840, 'adaptation': 134, 'retelling': 8889, 'literaryadaptation': 6441, 'thrillerleader': 11173, 'colony': 1950, 'woods': 12257, 'ape': 517, 'monkey': 7089, 'medicalresearch': 6831, 'plague': 8200, 'fantasyjapan': 4327, 'suicide': 10601, 'samurai': 9459, 'basedontruestory': 873, 'samuraisword': 9460, 'ronin': 9343, 'shogun': 9980, 'halfbreed': 5146, 'sciencefictionwashingtond': 9728, 'captainamerica': 1505, 'politicalthriller': 8310, 'familyogre': 4204, 'mystery': 7360, 'sciencefictioninventor': 9643, 'destiny': 2993, 'dreamer': 3608, 'futuristiccar': 4770, 'futuristiccity': 4771, 'comedybrotherbrotherrelationship': 2007, 'hero': 5279, 'talent': 10755, 'anotherdimension': 488, 'boygenius': 1242, 'hate': 5196, 'moraldilemma': 7119, 'teensuperheroes': 10849, 'deadbrother': 2867, 'adventuresupportgroup': 238, 'productplacement': 8488, 'bullying': 1373, 'racing': 8635, 'arcade': 547, 'medal': 6820, 'selfesteem': 9827, 'curiosity': 2774, 'precociouschild': 8402, 'firstpersonshooter': 4563, 'glitch': 4948, 'carefree': 1528, 'videogamer': 11830, 'bert': 984, 'interruptedwedding': 5910, 'socialreject': 10207, 'fantasysantaclaus': 4355, 'nerd': 7565, 'gift': 4917, 'bell': 974, 'beard': 921, 'northpole': 7685, 'chute': 1822, 'trestle': 11562, 'ticket': 11378, 'sciencefictionalternatehistory': 9570, 'familyflying': 4150, 'blacksmith': 1093, 'arena': 564, 'night': 7635, 'training': 11503, 'village': 11851, 'viking': 11849, 'ignorance': 5740, 'flight': 4594, 'nest': 7568, 'combat': 1963, 'well': 12091, 'warrior': 12006, 'manvsmachine': 6712, 'sunglasses': 10619, 'nanotechnology': 7487, 'rocketlauncher': 8981, 'firemen': 4551, 'veterinarian': 11816, 'fireengine': 4546, 'psychiatrist': 8539, 'adventuremarvelcomic': 209, 'spaceship': 10291, 'outerspace': 7871, 'adventurer': 224, 'fathersonrelationship': 4410, 'singleparent': 10075, 'nasa': 7502, 'expedition': 3967, 'wormhole': 12286, 'famine': 4267, 'blackhole': 1078, 'raceagainsttime': 8626, 'quantummechanics': 8608, 'familyrelationships': 4220, 'farmhouse': 4384, 'astronaut': 653, 'fatherdaughterrelationship': 4405, 'singlefather': 10073, 'farmer': 4383, 'spacestation': 10292, 'astrophysics': 656, 'zerogravity': 12356, 'timeparadox': 11394, 'relativity': 8814, 'adventurelossoflover': 206, 'dream': 3607, 'kidnapping': 6179, 'sleep': 10120, 'subconsciousness': 10571, 'heist': 5254, 'redemption': 8754, 'femalehero': 4444, 'sciencefictionmonster': 9661, 'godzilla': 4969, 'kaiju': 6139, 'toyko': 11473, 'actionriddle': 105, 'mountains': 7175, 'ring': 8944, 'goblin': 4962, 'tunnel': 11617, 'undergroundlake': 11694, 'buriedtreasure': 1385, 'climbingatree': 1886, 'invisibility': 5935, 'ancient': 420, 'gnomes': 4957, 'thrillerstreetgang': 11317, 'carrace': 1548, 'auto': 708, 'tuning': 11616, 'automobileracing': 716, 'romancediary': 9099, 'funeral': 4755, 'tea': 10808, 'travel': 11544, 'hospital': 5629, 'adventurecia': 175, 'mine': 6982, 'historicalfiction': 5336, 'nuclearwar': 7708, 'cubanmissilecrisis': 2753, 'worldwariii': 12285, '1960s': 10, 'sciencefictionrevolution': 9684, 'gameofdeath': 4792, 'dramawitch': 3599, 'fire': 4540, 'fountain': 4687, 'book': 1190, 'castle': 1579, 'apprentice': 535, 'merlin': 6886, 'mission': 7036, 'sorcerer': 10245, 'apprendista': 534, 'morgana': 7122, 'thrillernewyear': 11226, 'seve': 9875, 'drowning': 3631, 'cataclysm': 1585, 'lossoffather': 6528, 'atlanticocean': 663, 'ball': 784, 'self': 9825, 'abandonment': 24, 'giantwave': 4913, 'blackout': 1087, 'single': 10072, 'capsizedship': 1503, 'madhatter': 6623, 'familyambush': 4087, 'sadness': 9423, 'stage': 10401, 'liberationofprisoners': 6393, 'prince': 8451, 'donkey': 3193, 'theatreplay': 10926, 'conciliation': 2340, 'tricks': 11570, 'heirtothethrone': 5253, 'assault': 643, 'boardingschool': 1147, 'coupd': 2475, 'etat': 3893, 'teacher': 10809, 'cowardliness': 2496, 'pregnancy': 8407, 'capture': 1509, 'fantasyvideogame': 4376, 'chase': 1691, 'fictionallanguage': 4491, 'muscles': 7237, 'orc': 7836, 'adventuresavingtheworld': 228, 'fiction': 4484, 'goodvsevil': 4996, 'king': 6201, 'knifeheldtothroat': 6217, 'snowing': 10181, 'quest': 8617, 'history': 5339, 'warnurse': 11991, 'patriotism': 8011, 'hawaii': 5206, 'worldwarii': 12284, 'pilot': 8160, 'pearlharbor': 8022, 'airforce': 286, 'airplane': 292, 'pin': 8164, 'actiondestroy': 65, 'basedontoy': 871, 'teenagehero': 10831, 'romancearistotle': 9025, 'egypt': 3746, 'greece': 5048, 'persia': 8068, 'campaign': 1463, 'alexanderthegreat': 320, 'homosexuality': 5475, 'gayrelationship': 4839, 'ancientworld': 429, 'mysteryprophecy': 7434, 'lossoflover': 6533, 'cuttingthecord': 2787, 'childhero': 1743, 'dyinganddeath': 3693, 'sapprentice': 9480, 'blackmagic': 1082, 'sorcery': 10247, 'occultism': 7745, 'familymagic': 4187, 'chosenone': 1801, 'tournament': 11460, 'teenager': 10837, 'actionflying': 74, 'alcohol': 314, 'forbiddenlove': 4643, 'lovers': 6576, 'affection': 258, 'advertisingexpert': 251, 'alcoholism': 319, 'pokies': 8252, 'lostcivilisation': 6549, 'alone': 360, 'helplessness': 5267, 'virus': 11876, 'pandemic': 7926, 'fantasylondonengland': 4331, 'chocolate': 1792, 'factoryworker': 4036, 'parentskidsrelationship': 7963, 'candy': 1485, 'overweightchild': 7889, 'grandfathergrandsonrelationship': 5024, 'fantasyparis': 4348, 'brotherbrotherrelationship': 1330, 'expensiverestaurant': 3968, 'river': 8957, 'cook': 2415, 'mouse': 7182, 'confidence': 2356, 'roof': 9344, 'window': 12195, 'leavingone': 6342, 'sfamily': 9930, 'work': 12261, 'restaurantcritic': 8883, 'kitchen': 6209, 'spice': 10330, 'court': 2479, 'cookbook': 2416, 'chef': 1714, 'rat': 8695, 'dramahimalaya': 3395, 'martialarts': 6754, 'rivalry': 8956, 'ninja': 7653, 'hauntedbythepast': 5201, 'evildoctor': 3919, 'escapade': 3871, 'mastervillain': 6790, 'fightingcrime': 4505, 'unfulfillment': 11714, 'loveandromance': 6566, 'unfulfilledlove': 11713, 'animationafrica': 463, 'jealousy': 6035, 'dance': 2814, 'hunger': 5690, 'zoo': 12362, 'hippopotamus': 5331, 'chimp': 1775, 'penguin': 8041, 'volcano': 11890, 'madagascar': 6619, 'zebra': 12354, 'shark': 9948, 'familymuseum': 4196, 'theodoreroosevelt': 10942, 'ameliaearhart': 389, 'smithsonian': 10148, 'sciencefictioncorruption': 9600, 'boxer': 1227, 'flying': 4622, 'philosophy': 8113, 'kungfu': 6243, 'undergroundworld': 11695, 'temple': 10872, 'subway': 10587, 'fight': 4499, 'sunlight': 10621, 'computervirus': 2328, 'precognition': 8404, 'supercomputer': 10626, 'machinetown': 6615, 'yingyang': 12328, 'virtualreality': 11875, 'worldreligion': 12280, 'truth': 11606, 'cyberpunk': 2790, 'yinyang': 12329, 'gnosticism': 4958, 'familyqueen': 4218, 'betrayal': 991, 'snowman': 10183, 'reindeer': 8807, 'curse': 2777, 'snow': 10177, 'troll': 11579, 'mountainclimber': 7170, 'plato': 8219, 'rave': 8698, 'fantasymarvelcomic': 4336, 'hostiletakeover': 5639, 'norsemythology': 7676, 'asgard': 625, 'thrillerfuture': 11115, 'australia': 697, 'survival': 10673, 'ontherun': 7818, 'convoy': 2414, 'peakoil': 8021, 'darkfuture': 2841, 'mysteryrome': 7439, 'vatican': 11790, 'symbolism': 10735, 'christian': 1803, 'illuminati': 5751, 'prequel': 8424, 'antimatter': 503, 'conspiracy': 2381, 'investigator': 5931, 'catholicism': 1600, 'cern': 1649, 'actionnewmexico': 94, 'banishment': 804, 'hammer': 5158, 'odin': 7756, 'heimdall': 5249, 'comedyhamster': 2087, 'kidsandfamily': 6182, 'catvsdog': 1612, 'dogcatfriendship': 3170, 'animallead': 448, 'girldogrelationship': 4927, 'comedydyr': 2058, 'adventureunderworld': 243, 'hades': 5134, 'mythology': 7475, 'greekmythology': 5055, 'zeus': 12357, 'perseus': 8067, 'gods': 4968, 'ancientgreece': 426, 'basedongreekmyth': 861, 'ares': 565, 'fantasywitch': 4377, 'imprisonment': 5787, 'vampire': 11777, 'fishoutofwater': 4571, 'chains': 1655, 'gothic': 5006, 'madness': 6626, 'oldhouse': 7787, 'lo

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int64)

In [103]:
genkey_sim = cosine_similarity(movie_genkey_mat, movie_genkey_mat)
print(genkey_sim.shape)
genkey_sim[:10, :10]

(4803, 4803)

array([[1.        , 0.09365858, 0.13608276, 0.04082483, 0.24056261,
        0.09365858, 0.        , 0.18463724, 0.12909944, 0.12309149],
       [0.09365858, 1.        , 0.07647191, 0.        , 0.05407381,
        0.15789474, 0.        , 0.06917145, 0.14509525, 0.06917145],
       [0.13608276, 0.07647191, 1.        , 0.06666667, 0.15713484,
        0.15294382, 0.        , 0.30151134, 0.10540926, 0.20100756],
       [0.04082483, 0.        , 0.06666667, 1.        , 0.04714045,
        0.09176629, 0.        , 0.12060454, 0.        , 0.18090681],
       [0.24056261, 0.05407381, 0.15713484, 0.04714045, 1.        ,
        0.05407381, 0.05555556, 0.21320072, 0.0745356 , 0.14213381],
       [0.09365858, 0.15789474, 0.15294382, 0.09176629, 0.05407381,
        1.        , 0.        , 0.20751434, 0.07254763, 0.20751434],
       [0.        , 0.        , 0.        , 0.        , 0.05555556,
        0.        , 1.        , 0.07106691, 0.0745356 , 0.        ],
       [0.18463724, 0.06917145, 0.30151134, 0.12060454, 0.21320072,
        0.20751434, 0.07106691, 1.        , 0.09534626, 0.36363636],
       [0.12909944, 0.14509525, 0.10540926, 0.        , 0.0745356 ,
        0.07254763, 0.0745356 , 0.09534626, 1.        , 0.09534626],
       [0.12309149, 0.06917145, 0.20100756, 0.18090681, 0.14213381,
        0.20751434, 0.        , 0.36363636, 0.09534626, 1.        ]])

In [104]:
movie_idx_by_genkey_sim_desc = genkey_sim.argsort(axis=-1)[:, ::-1]
print(movie_idx_by_genkey_sim_desc.shape)

print(movie_idx_by_genkey_sim_desc[0, :10])

(4803, 4803)
[   0   71   47 2681 2708 1324   83   61 1201 2327]

In [106]:
def recommand_genre_keyword_similar_movies(title, top_n=10):
    
    index = movie_df[movie_df['title'] == title].index.values[0]
    
    rcmd_movie_df = movie_df.iloc[movie_idx_by_genkey_sim_desc[index, :top_n * 2]]
   
    rcmd_movie_df = rcmd_movie_df[rcmd_movie_df.index != index]
    
    return rcmd_movie_df.sort_values('vote_average', ascending=False)[:top_n]

recommand_genre_keyword_similar_movies('Avatar', 10)

,id,title,genres,vote_average,vote_count,popularity,keywords,overview,weighted_vote_average,genres + keywords
47,54138,Star Trek Into Darkness,Action Adventure ScienceFiction,7.4,4418,78.291018,spacecraft friendship sequel futuristic space ...,When the crew of the Enterprise is called back...,7.298885,Action Adventure ScienceFictionspacecraft frie...
2327,106,Predator,ScienceFiction Action Adventure Thriller,7.3,2093,50.009408,centralandsouthamerica predator alien stalking...,Dutch and his group of commandos are hired by ...,7.118473,ScienceFiction Action Adventure Thrillercentra...
3405,13001,Stargate: The Ark of Truth,Adventure ScienceFiction,6.9,140,8.591387,wormhole spacetravel supernaturalpowers spaces...,SG-1 searches for an ancient weapon which coul...,6.313841,Adventure ScienceFictionwormhole spacetravel s...
2161,9588,Quigley Down Under,Romance Action Adventure Western Drama,6.5,119,11.360997,australian chase,American Matt Quigley answers Australian land ...,6.191378,Romance Action Adventure Western Dramaaustrali...
17,1865,Pirates of the Caribbean: On Stranger Tides,Adventure Action Fantasy,6.4,4948,135.413856,sea captain mutiny sword primeminister sailing...,Captain Jack Sparrow crosses paths with a woma...,6.378572,Adventure Action Fantasysea captain mutiny swo...
2681,15173,Jonah: A VeggieTales Movie,Action Adventure Animation Comedy Family Fanta...,6.4,22,1.446172,,"Get ready as Bob the Tomato, Larry the Cucumbe...",6.109439,Action Adventure Animation Comedy Family Fanta...
643,5551,Space Cowboys,Action Adventure Thriller,6.3,403,15.772081,nasa spacetravel astronaut elderly,"Frank Corvin, ‘Hawk’ Hawkins, Jerry O'Neill an...",6.200494,Action Adventure Thrillernasa spacetravel astr...
4,49529,John Carter,Action Adventure ScienceFiction,6.1,2124,43.926995,basedonnovel mars medallion spacetravel prince...,"John Carter is a war-weary, former military ca...",6.098838,Action Adventure ScienceFictionbasedonnovel ma...
86,10192,Shrek Forever After,Comedy Adventure Fantasy Animation Family,6.0,1959,44.041186,ogre 3d,A bored and domesticated Shrek pacts with deal...,6.014650,Comedy Adventure Fantasy Animation Familyogre 3d
1201,34851,Predators,Action ScienceFiction Adventure Thriller,6.0,1206,47.649554,hunter predator yakuza huntinghumanbeings alie...,A mercenary reluctantly leads a motley crew of...,6.021648,Action ScienceFiction Adventure Thrillerhunter...